### ISSUE TITLE
[Question] Get TextContent (TextEquiv) index

### ISSUE THREAD

**Issue by maxnth** [PRImA-Research-Lab/prima-core-libs#4]
Is it possible to retrieve the value of the _index_ attribute for a given TextEquiv (textContent)-element with the current version of prima-core-libs? 
I'm using schema version ```2017-07-15``` and upwards and (if I'm not mistaken) the attribute should be allowed for TextEquiv-elements. 

I can't find the the attribute in the ```VariableMap``` returned by the ```.getAttributes()``` method (unlike _dataType_ or _comments_ for example) even if the attribute is set and has a valid value. 
As far as I can see there's no explicit getter-method for the (sort) index for textContent objects either.

When using (for example) the following PAGE XML snippet (from [0030.zip](https://github.com/PRImA-Research-Lab/prima-core-libs/files/4224463/0030.zip))
```
<TextEquiv dataType="xsd:boolean" comments="comment" conf="0.5" index="1">
    <Unicode>մարդիկ ։ Սակայն իբրեւ տեսին ըզ_</Unicode>
</TextEquiv>
```
I can access the dataType, conf or comments via their associated getter-method or using 
```
textContent.getAttributes().get("dataType").getValue()
textContent.getAttributes().get("conf").getValue()
textContent.getAttributes().get("comments").getValue()
```
But 
```
textContent.getAttributes().get("index")
```
will always return null.

Is this a misunderstanding/false usage of the library from my side or actually not possible at the moment/not intended to work that way?

**Comment by chris1010010** [comment]
Thanks for pointing this out. Should be fixed by the latest commit.

**Comment by maxnth** [comment]
@chris1010010 thank you very much for the fix but it seems that one also needs to make the same change (```if ("int".equals(type) || "integer".equals(type))```) at
https://github.com/PRImA-Research-Lab/prima-core-libs/blob/12923531592b74165ddd0fa48dfc111d3a190623/java/PrimaIo/src/org/primaresearch/io/xml/DefaultSchemaParser.java#L299-L300
to actually get the expected results.
After changing the aforementioned if statement as well, everything worked perfectly for me.

**Comment by chris1010010** [comment]
Good spot! Yes, indeed

**Comment by chris1010010** [comment]
I guess that's duplicated code and should be changed anyway.

**Comment by chris1010010** [comment]
Changes uploaded
